### PR TITLE
Feat: Added github action that will format on push

### PR DESCRIPTION
**Pull request by raythurman2386**
Co-authored-by: danielle baxter <danibaxx@hotmail.com>
# Description
Added a github action that runs the format script in our package json

- [x] New feature (non-breaking change which adds functionality)

## Change Status

- [x] Complete, tested, ready to review and merge

# How Has This Been Tested?

- [x] Used in personal project to test, migrated over to Nusite project and pushed changes to ensure it was working properly.

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] There are no merge conflicts

### CODE REVIEW

**Comment by raythurman2386** [comment]
[Implement Github Action for formatting](https://trello.com/c/UWKjS7ds/57-implement-github-action-for-formatting)

**Comment by KAfable** [comment]
Are there any conflicts with this right now versus the prettierrc settings? Most of the time formatting on save with prettier should fix this.

**Comment by raythurman2386** [comment]
This works along with the prettier settings. It just enforces that our formatting will always match what is in our prettierrc file regardless even if we forget to format before we push up ourselves.

**Comment by KAfable** [comment]
But shouldn't prettier format anyways on save so we can't really forget to format?

**Comment by raythurman2386** [comment]
That all depends on if the user has it set up in their Global vs code settings. Otherwise it will "format" but not necessarily to the prettier config. If you'll notice it formatted all the code when I pushed it up and I even have format on code set up. Not always best to just rely on the Text editor, or the user to hit format before pushing. This automates the entire thing.

**Comment by KAfable** [comment]
Per our conversation in stand up, looks good to me.

**Pull request merged**
